import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/tanstackQueries/tanstackProvider";
import { ToastContainer } from "react-toastify";
import { AppProvider } from "@/context/AppContext";
import { SocketProvider } from "@/context/SocketContext";

export const metadata: Metadata = {
  title: "Chatty Darling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <SocketProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
          </SocketProvider>
        </AppProvider>

        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        // transition={Bounce}
        />
      </body>
    </html>
  );
}
